apiVersion: v1
kind: Service
metadata:
  name: geoapp-service
spec:
  type: LoadBalancer
  selector:
    app: geoapp
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379